---
swagger: "2.0"
info:
  description: "Machine Learning"
  version: "1.0.0"
  title: "Machine Learning"
  contact:
    email: "jalasoft@jalasoft.com"
host: "127.0.0.1:5000"
tags:
- name: "Iris recognition"
  description: "Train and recognize an iris"
  externalDocs:
    description: "Train and recognize an iris"
    url: "http://127.0.0.1:5000"
- name: "Object recognition"
  description: "Vgg16, Resnet, Inception V3"
  externalDocs:
    description: "Object recognition"
    url: "http://127.0.0.1:5000"
- name: "Face recognition"
  description: "VggFace"
  externalDocs:
    description: "Face recognition"
    url: "http://127.0.0.1:5000"
- name: "Emotion recognition"
  description: "Emotion"
  externalDocs:
    description: "Emotion recognition"
    url: "http://127.0.0.1:5000"
schemes:
- "http"
paths:
  /iris_recognition:
    post:
      tags:
      - "Iris recognition"
      summary: "Search a name"
      description: ""
      operationId: "update_name_with_form"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Upload the iris"
        required: true
        type: "file"
      - name: "percentage"
        in: "formData"
        description: "Percentage between 0-1"
        required: true
        type: "number"
        format: "float"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessIrisPost"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
        "500":
          description: "Server Error"
      x-swagger-router-controller: "swagger_server.controllers.iris_recognition_controller"
  /iris_recognition_train:
    post:
      tags:
      - "Iris recognition"
      summary: "Training the model"
      description: ""
      operationId: "update_data_with_form"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "zip"
        in: "formData"
        description: "Upload irises"
        required: true
        type: "file"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
        "500":
          description: "Server Error"
      x-swagger-router-controller: "swagger_server.controllers.iris_recognition_controller"
  /object_recognizer:
    post:
      tags:
      - "Object recognition"
      summary: "Search an object"
      description: ""
      operationId: "update_object_with_form"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "file of pictures"
        required: true
        type: "file"
      - name: "name"
        in: "formData"
        description: "Name of the object to search"
        required: true
        type: "string"
      - name: "model"
        in: "formData"
        description: "ModelVgg16, InceptionV3, Resnet"
        required: true
        type: "string"
      - name: "percentage"
        in: "formData"
        description: "Percentage between 0-1"
        required: true
        type: "number"
        format: "float"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessObjectRecognitionPost"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
        "500":
          description: "Server Error"
      x-swagger-router-controller: "swagger_server.controllers.object_recognition_controller"
  /vggface_search_person:
    post:
      tags:
      - "Face recognition"
      summary: "Search an object"
      description: ""
      operationId: "update_face_with_form"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Zip file"
        required: true
        type: "file"
      - name: "person"
        in: "formData"
        description: "Image of person face to search"
        required: true
        type: "file"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessFaceRecognitionPost"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
        "500":
          description: "Server Error"
      x-swagger-router-controller: "swagger_server.controllers.face_recognition_controller"
  /Emotion:
    post:
      tags:
      - "Emotion recognition"
      summary: "Recognize a face emotion"
      description: ""
      operationId: "update_emotion_with_form"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "Image file"
        required: true
        type: "file"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessEmotionPost"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "Not found"
        "405":
          description: "Invalid input"
        "500":
          description: "Server Error"
      x-swagger-router-controller: "swagger_server.controllers.emotion_recognition_controller"
definitions:
  Object:
    type: "object"
    properties:
      Name:
        type: "string"
      Time:
        type: "string"
      Percentage:
        type: "number"
        format: "float"
    example:
      Percentage: 0.8008282
      Time: "Time"
      Name: "Name"
  Object2:
    properties:
      The person appears in:
        type: "string"
    example:
      The person appears in: "The person appears in"
  Object4:
    properties:
      http://127.0.0.1:5000/downloader/saved_files/compress_files/:
        type: "string"
    example:
      http://127.0.0.1:5000/downloader/saved_files/compress_files/: "http://127.0.0.1:5000/downloader/saved_files/compress_files/"
  SuccessIrisPost:
    type: "object"
    properties:
      Name:
        type: "string"
      Percentage:
        type: "number"
        format: "float"
    example:
      Percentage: 0.8008282
      Name: "Name"
  SuccessObjectRecognitionPost:
    type: "object"
    properties:
      object:
        $ref: "#/definitions/Object"
    example:
      object:
        Percentage: 0.8008282
        Time: "Time"
        Name: "Name"
  SuccessFaceRecognitionPost:
    properties:
      array:
        $ref: "#/definitions/Object2"
    example:
      array:
        The person appears in: "The person appears in"
  SuccessEmotionPost:
    properties:
      URL:
        $ref: "#/definitions/Object4"
    example:
      URL:
        http://127.0.0.1:5000/downloader/saved_files/compress_files/: "http://127.0.0.1:5000/downloader/saved_files/compress_files/"
