# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object
from swagger_server import util


class SuccessObjectRecognitionPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, object: Object=None):  # noqa: E501
        """SuccessObjectRecognitionPost - a model defined in Swagger

        :param object: The object of this SuccessObjectRecognitionPost.  # noqa: E501
        :type object: Object
        """
        self.swagger_types = {
            'object': Object
        }

        self.attribute_map = {
            'object': 'object'
        }

        self._object = object

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessObjectRecognitionPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessObjectRecognitionPost of this SuccessObjectRecognitionPost.  # noqa: E501
        :rtype: SuccessObjectRecognitionPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object(self) -> Object:
        """Gets the object of this SuccessObjectRecognitionPost.


        :return: The object of this SuccessObjectRecognitionPost.
        :rtype: Object
        """
        return self._object

    @object.setter
    def object(self, object: Object):
        """Sets the object of this SuccessObjectRecognitionPost.


        :param object: The object of this SuccessObjectRecognitionPost.
        :type object: Object
        """

        self._object = object
