# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessCountryPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, person_country: str=None, quantity: int=None):  # noqa: E501
        """SuccessCountryPost - a model defined in Swagger

        :param person_country: The person_country of this SuccessCountryPost.  # noqa: E501
        :type person_country: str
        :param quantity: The quantity of this SuccessCountryPost.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'person_country': str,
            'quantity': int
        }

        self.attribute_map = {
            'person_country': 'person_country',
            'quantity': 'quantity'
        }

        self._person_country = person_country
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessCountryPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessCountryPost of this SuccessCountryPost.  # noqa: E501
        :rtype: SuccessCountryPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def person_country(self) -> str:
        """Gets the person_country of this SuccessCountryPost.


        :return: The person_country of this SuccessCountryPost.
        :rtype: str
        """
        return self._person_country

    @person_country.setter
    def person_country(self, person_country: str):
        """Sets the person_country of this SuccessCountryPost.


        :param person_country: The person_country of this SuccessCountryPost.
        :type person_country: str
        """

        self._person_country = person_country

    @property
    def quantity(self) -> int:
        """Gets the quantity of this SuccessCountryPost.


        :return: The quantity of this SuccessCountryPost.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this SuccessCountryPost.


        :param quantity: The quantity of this SuccessCountryPost.
        :type quantity: int
        """

        self._quantity = quantity
