# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _date: str=None, start_time: str=None, end_time: str=None, state: str=None, resource_name: str=None, resource_type: str=None, resource_model: str=None, resource_state: str=None, person_gender: str=None, person_full_name: str=None, person_age: int=None, person_country: str=None, person_city: str=None):  # noqa: E501
        """SuccessPost - a model defined in Swagger

        :param _date: The _date of this SuccessPost.  # noqa: E501
        :type _date: str
        :param start_time: The start_time of this SuccessPost.  # noqa: E501
        :type start_time: str
        :param end_time: The end_time of this SuccessPost.  # noqa: E501
        :type end_time: str
        :param state: The state of this SuccessPost.  # noqa: E501
        :type state: str
        :param resource_name: The resource_name of this SuccessPost.  # noqa: E501
        :type resource_name: str
        :param resource_type: The resource_type of this SuccessPost.  # noqa: E501
        :type resource_type: str
        :param resource_model: The resource_model of this SuccessPost.  # noqa: E501
        :type resource_model: str
        :param resource_state: The resource_state of this SuccessPost.  # noqa: E501
        :type resource_state: str
        :param person_gender: The person_gender of this SuccessPost.  # noqa: E501
        :type person_gender: str
        :param person_full_name: The person_full_name of this SuccessPost.  # noqa: E501
        :type person_full_name: str
        :param person_age: The person_age of this SuccessPost.  # noqa: E501
        :type person_age: int
        :param person_country: The person_country of this SuccessPost.  # noqa: E501
        :type person_country: str
        :param person_city: The person_city of this SuccessPost.  # noqa: E501
        :type person_city: str
        """
        self.swagger_types = {
            '_date': str,
            'start_time': str,
            'end_time': str,
            'state': str,
            'resource_name': str,
            'resource_type': str,
            'resource_model': str,
            'resource_state': str,
            'person_gender': str,
            'person_full_name': str,
            'person_age': int,
            'person_country': str,
            'person_city': str
        }

        self.attribute_map = {
            '_date': 'date',
            'start_time': 'start_time',
            'end_time': 'end_time',
            'state': 'state',
            'resource_name': 'resource_name',
            'resource_type': 'resource_type',
            'resource_model': 'resource_model',
            'resource_state': 'resource_state',
            'person_gender': 'person_gender',
            'person_full_name': 'person_full_name',
            'person_age': 'person_age',
            'person_country': 'person_country',
            'person_city': 'person_city'
        }

        self.__date = _date
        self._start_time = start_time
        self._end_time = end_time
        self._state = state
        self._resource_name = resource_name
        self._resource_type = resource_type
        self._resource_model = resource_model
        self._resource_state = resource_state
        self._person_gender = person_gender
        self._person_full_name = person_full_name
        self._person_age = person_age
        self._person_country = person_country
        self._person_city = person_city

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessPost of this SuccessPost.  # noqa: E501
        :rtype: SuccessPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this SuccessPost.


        :return: The _date of this SuccessPost.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this SuccessPost.


        :param _date: The _date of this SuccessPost.
        :type _date: str
        """

        self.__date = _date

    @property
    def start_time(self) -> str:
        """Gets the start_time of this SuccessPost.


        :return: The start_time of this SuccessPost.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """Sets the start_time of this SuccessPost.


        :param start_time: The start_time of this SuccessPost.
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self) -> str:
        """Gets the end_time of this SuccessPost.


        :return: The end_time of this SuccessPost.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """Sets the end_time of this SuccessPost.


        :param end_time: The end_time of this SuccessPost.
        :type end_time: str
        """

        self._end_time = end_time

    @property
    def state(self) -> str:
        """Gets the state of this SuccessPost.


        :return: The state of this SuccessPost.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this SuccessPost.


        :param state: The state of this SuccessPost.
        :type state: str
        """

        self._state = state

    @property
    def resource_name(self) -> str:
        """Gets the resource_name of this SuccessPost.


        :return: The resource_name of this SuccessPost.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: str):
        """Sets the resource_name of this SuccessPost.


        :param resource_name: The resource_name of this SuccessPost.
        :type resource_name: str
        """

        self._resource_name = resource_name

    @property
    def resource_type(self) -> str:
        """Gets the resource_type of this SuccessPost.


        :return: The resource_type of this SuccessPost.
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type: str):
        """Sets the resource_type of this SuccessPost.


        :param resource_type: The resource_type of this SuccessPost.
        :type resource_type: str
        """

        self._resource_type = resource_type

    @property
    def resource_model(self) -> str:
        """Gets the resource_model of this SuccessPost.


        :return: The resource_model of this SuccessPost.
        :rtype: str
        """
        return self._resource_model

    @resource_model.setter
    def resource_model(self, resource_model: str):
        """Sets the resource_model of this SuccessPost.


        :param resource_model: The resource_model of this SuccessPost.
        :type resource_model: str
        """

        self._resource_model = resource_model

    @property
    def resource_state(self) -> str:
        """Gets the resource_state of this SuccessPost.


        :return: The resource_state of this SuccessPost.
        :rtype: str
        """
        return self._resource_state

    @resource_state.setter
    def resource_state(self, resource_state: str):
        """Sets the resource_state of this SuccessPost.


        :param resource_state: The resource_state of this SuccessPost.
        :type resource_state: str
        """

        self._resource_state = resource_state

    @property
    def person_gender(self) -> str:
        """Gets the person_gender of this SuccessPost.


        :return: The person_gender of this SuccessPost.
        :rtype: str
        """
        return self._person_gender

    @person_gender.setter
    def person_gender(self, person_gender: str):
        """Sets the person_gender of this SuccessPost.


        :param person_gender: The person_gender of this SuccessPost.
        :type person_gender: str
        """

        self._person_gender = person_gender

    @property
    def person_full_name(self) -> str:
        """Gets the person_full_name of this SuccessPost.


        :return: The person_full_name of this SuccessPost.
        :rtype: str
        """
        return self._person_full_name

    @person_full_name.setter
    def person_full_name(self, person_full_name: str):
        """Sets the person_full_name of this SuccessPost.


        :param person_full_name: The person_full_name of this SuccessPost.
        :type person_full_name: str
        """

        self._person_full_name = person_full_name

    @property
    def person_age(self) -> int:
        """Gets the person_age of this SuccessPost.


        :return: The person_age of this SuccessPost.
        :rtype: int
        """
        return self._person_age

    @person_age.setter
    def person_age(self, person_age: int):
        """Sets the person_age of this SuccessPost.


        :param person_age: The person_age of this SuccessPost.
        :type person_age: int
        """

        self._person_age = person_age

    @property
    def person_country(self) -> str:
        """Gets the person_country of this SuccessPost.


        :return: The person_country of this SuccessPost.
        :rtype: str
        """
        return self._person_country

    @person_country.setter
    def person_country(self, person_country: str):
        """Sets the person_country of this SuccessPost.


        :param person_country: The person_country of this SuccessPost.
        :type person_country: str
        """

        self._person_country = person_country

    @property
    def person_city(self) -> str:
        """Gets the person_city of this SuccessPost.


        :return: The person_city of this SuccessPost.
        :rtype: str
        """
        return self._person_city

    @person_city.setter
    def person_city(self, person_city: str):
        """Sets the person_city of this SuccessPost.


        :param person_city: The person_city of this SuccessPost.
        :type person_city: str
        """

        self._person_city = person_city
