# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessLocationPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, person_city: str=None, quantity: int=None):  # noqa: E501
        """SuccessLocationPost - a model defined in Swagger

        :param person_city: The person_city of this SuccessLocationPost.  # noqa: E501
        :type person_city: str
        :param quantity: The quantity of this SuccessLocationPost.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'person_city': str,
            'quantity': int
        }

        self.attribute_map = {
            'person_city': 'person_city',
            'quantity': 'quantity'
        }

        self._person_city = person_city
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessLocationPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessLocationPost of this SuccessLocationPost.  # noqa: E501
        :rtype: SuccessLocationPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def person_city(self) -> str:
        """Gets the person_city of this SuccessLocationPost.


        :return: The person_city of this SuccessLocationPost.
        :rtype: str
        """
        return self._person_city

    @person_city.setter
    def person_city(self, person_city: str):
        """Sets the person_city of this SuccessLocationPost.


        :param person_city: The person_city of this SuccessLocationPost.
        :type person_city: str
        """

        self._person_city = person_city

    @property
    def quantity(self) -> int:
        """Gets the quantity of this SuccessLocationPost.


        :return: The quantity of this SuccessLocationPost.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this SuccessLocationPost.


        :param quantity: The quantity of this SuccessLocationPost.
        :type quantity: int
        """

        self._quantity = quantity
