#
# @body_booking_post.py Copyright (c) 2022 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# Edificio Union № 1376 Av. General Inofuentes esquina Calle 20, La Paz, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401
from swagger_server.models.base_model_ import Model
from swagger_server.models.details import Details  # noqa: F401,E501
from swagger_server.models.person import Person  # noqa: F401,E501
from swagger_server.models.resource import Resource  # noqa: F401,E501
from swagger_server.models.schedule import Schedule  # noqa: F401,E501
from swagger_server import util


class BodyBookingPost(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, details: Details=None, schedule: Schedule=None, state: str=None, type: str=None, resource: Resource=None, person: Person=None):  # noqa: E501
        """BodyBookingPost - a model defined in Swagger

        :param details: The details of this BodyBookingPost.  # noqa: E501
        :type details: Details
        :param schedule: The schedule of this BodyBookingPost.  # noqa: E501
        :type schedule: Schedule
        :param state: The state of this BodyBookingPost.  # noqa: E501
        :type state: str
        :param type: The type of this BodyBookingPost.  # noqa: E501
        :type type: str
        :param resource: The resource of this BodyBookingPost.  # noqa: E501
        :type resource: Resource
        :param person: The person of this BodyBookingPost.  # noqa: E501
        :type person: Person
        """
        self.swagger_types = {
            'details': Details,
            'schedule': Schedule,
            'state': str,
            'type': str,
            'resource': Resource,
            'person': Person
        }

        self.attribute_map = {
            'details': 'details',
            'schedule': 'schedule',
            'state': 'state',
            'type': 'type',
            'resource': 'resource',
            'person': 'person'
        }

        self._details = details
        self._schedule = schedule
        self._state = state
        self._type = type
        self._resource = resource
        self._person = person

    @classmethod
    def from_dict(cls, dikt) -> 'BodyBookingPost':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BodyBookingPost of this BodyBookingPost.  # noqa: E501
        :rtype: BodyBookingPost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def details(self) -> Details:
        """Gets the details of this BodyBookingPost.


        :return: The details of this BodyBookingPost.
        :rtype: Details
        """
        return self._details

    @details.setter
    def details(self, details: Details):
        """Sets the details of this BodyBookingPost.


        :param details: The details of this BodyBookingPost.
        :type details: Details
        """

        self._details = details

    @property
    def schedule(self) -> Schedule:
        """Gets the schedule of this BodyBookingPost.


        :return: The schedule of this BodyBookingPost.
        :rtype: Schedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule: Schedule):
        """Sets the schedule of this BodyBookingPost.


        :param schedule: The schedule of this BodyBookingPost.
        :type schedule: Schedule
        """

        self._schedule = schedule

    @property
    def state(self) -> str:
        """Gets the state of this BodyBookingPost.


        :return: The state of this BodyBookingPost.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this BodyBookingPost.


        :param state: The state of this BodyBookingPost.
        :type state: str
        """

        self._state = state

    @property
    def type(self) -> str:
        """Gets the type of this BodyBookingPost.


        :return: The type of this BodyBookingPost.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this BodyBookingPost.


        :param type: The type of this BodyBookingPost.
        :type type: str
        """

        self._type = type

    @property
    def resource(self) -> Resource:
        """Gets the resource of this BodyBookingPost.


        :return: The resource of this BodyBookingPost.
        :rtype: Resource
        """
        return self._resource

    @resource.setter
    def resource(self, resource: Resource):
        """Sets the resource of this BodyBookingPost.


        :param resource: The resource of this BodyBookingPost.
        :type resource: Resource
        """

        self._resource = resource

    @property
    def person(self) -> Person:
        """Gets the person of this BodyBookingPost.


        :return: The person of this BodyBookingPost.
        :rtype: Person
        """
        return self._person

    @person.setter
    def person(self, person: Person):
        """Sets the person of this BodyBookingPost.


        :param person: The person of this BodyBookingPost.
        :type person: Person
        """

        self._person = person
