#
# @schedule.py Copyright (c) 2022 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# Edificio Union № 1376 Av. General Inofuentes esquina Calle 20, La Paz, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401
from swagger_server.models.base_model_ import Model
from swagger_server import util


class Schedule(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _date: str=None, start_time: str=None, end_time: str=None):  # noqa: E501
        """Schedule - a model defined in Swagger

        :param _date: The _date of this Schedule.  # noqa: E501
        :type _date: str
        :param start_time: The start_time of this Schedule.  # noqa: E501
        :type start_time: str
        :param end_time: The end_time of this Schedule.  # noqa: E501
        :type end_time: str
        """
        self.swagger_types = {
            '_date': str,
            'start_time': str,
            'end_time': str
        }

        self.attribute_map = {
            '_date': 'date',
            'start_time': 'start_time',
            'end_time': 'end_time'
        }

        self.__date = _date
        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'Schedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Schedule of this Schedule.  # noqa: E501
        :rtype: Schedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this Schedule.

        MM/DD/YYYY  # noqa: E501

        :return: The _date of this Schedule.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this Schedule.

        MM/DD/YYYY  # noqa: E501

        :param _date: The _date of this Schedule.
        :type _date: str
        """

        self.__date = _date

    @property
    def start_time(self) -> str:
        """Gets the start_time of this Schedule.

        HH:MM:SS  # noqa: E501

        :return: The start_time of this Schedule.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """Sets the start_time of this Schedule.

        HH:MM:SS  # noqa: E501

        :param start_time: The start_time of this Schedule.
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self) -> str:
        """Gets the end_time of this Schedule.

        HH:MM:SS  # noqa: E501

        :return: The end_time of this Schedule.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """Sets the end_time of this Schedule.

        HH:MM:SS  # noqa: E501

        :param end_time: The end_time of this Schedule.
        :type end_time: str
        """

        self._end_time = end_time
