#
# @success_booking_get.py Copyright (c) 2022 Jalasoft.
# 2643 Av Melchor Perez de Olguin, Colquiri Sud, Cochabamba, Bolivia.
# Edificio Union № 1376 Av. General Inofuentes esquina Calle 20, La Paz, Bolivia.
# All rights reserved.
#
# This software is the confidential and proprietary information of
# Jalasoft, ("Confidential Information"). You shall not
# disclose such Confidential Information and shall use it only in
# accordance with the terms of the license agreement you entered into
# with Jalasoft.
#

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401
from swagger_server.models.base_model_ import Model
from swagger_server.models.details import Details  # noqa: F401,E501
from swagger_server.models.person import Person  # noqa: F401,E501
from swagger_server.models.resource import Resource  # noqa: F401,E501
from swagger_server.models.schedule import Schedule  # noqa: F401,E501
from swagger_server import util


class SuccessBookingGet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, delete: int=None, details: Details=None, schedule: Schedule=None, state: str=None, type: str=None, resource: Resource=None, person: Person=None):  # noqa: E501
        """SuccessBookingGet - a model defined in Swagger

        :param id: The id of this SuccessBookingGet.  # noqa: E501
        :type id: str
        :param delete: The delete of this SuccessBookingGet.  # noqa: E501
        :type delete: int
        :param details: The details of this SuccessBookingGet.  # noqa: E501
        :type details: Details
        :param schedule: The schedule of this SuccessBookingGet.  # noqa: E501
        :type schedule: Schedule
        :param state: The state of this SuccessBookingGet.  # noqa: E501
        :type state: str
        :param type: The type of this SuccessBookingGet.  # noqa: E501
        :type type: str
        :param resource: The resource of this SuccessBookingGet.  # noqa: E501
        :type resource: Resource
        :param person: The person of this SuccessBookingGet.  # noqa: E501
        :type person: Person
        """
        self.swagger_types = {
            'id': str,
            'delete': int,
            'details': Details,
            'schedule': Schedule,
            'state': str,
            'type': str,
            'resource': Resource,
            'person': Person
        }

        self.attribute_map = {
            'id': '_id',
            'delete': 'delete',
            'details': 'details',
            'schedule': 'schedule',
            'state': 'state',
            'type': 'type',
            'resource': 'resource',
            'person': 'person'
        }

        self._id = id
        self._delete = delete
        self._details = details
        self._schedule = schedule
        self._state = state
        self._type = type
        self._resource = resource
        self._person = person

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessBookingGet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessBookingGet of this SuccessBookingGet.  # noqa: E501
        :rtype: SuccessBookingGet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this SuccessBookingGet.


        :return: The id of this SuccessBookingGet.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this SuccessBookingGet.


        :param id: The id of this SuccessBookingGet.
        :type id: str
        """

        self._id = id

    @property
    def delete(self) -> int:
        """Gets the delete of this SuccessBookingGet.


        :return: The delete of this SuccessBookingGet.
        :rtype: int
        """
        return self._delete

    @delete.setter
    def delete(self, delete: int):
        """Sets the delete of this SuccessBookingGet.


        :param delete: The delete of this SuccessBookingGet.
        :type delete: int
        """

        self._delete = delete

    @property
    def details(self) -> Details:
        """Gets the details of this SuccessBookingGet.


        :return: The details of this SuccessBookingGet.
        :rtype: Details
        """
        return self._details

    @details.setter
    def details(self, details: Details):
        """Sets the details of this SuccessBookingGet.


        :param details: The details of this SuccessBookingGet.
        :type details: Details
        """

        self._details = details

    @property
    def schedule(self) -> Schedule:
        """Gets the schedule of this SuccessBookingGet.


        :return: The schedule of this SuccessBookingGet.
        :rtype: Schedule
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule: Schedule):
        """Sets the schedule of this SuccessBookingGet.


        :param schedule: The schedule of this SuccessBookingGet.
        :type schedule: Schedule
        """

        self._schedule = schedule

    @property
    def state(self) -> str:
        """Gets the state of this SuccessBookingGet.


        :return: The state of this SuccessBookingGet.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this SuccessBookingGet.


        :param state: The state of this SuccessBookingGet.
        :type state: str
        """

        self._state = state

    @property
    def type(self) -> str:
        """Gets the type of this SuccessBookingGet.


        :return: The type of this SuccessBookingGet.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this SuccessBookingGet.


        :param type: The type of this SuccessBookingGet.
        :type type: str
        """

        self._type = type

    @property
    def resource(self) -> Resource:
        """Gets the resource of this SuccessBookingGet.


        :return: The resource of this SuccessBookingGet.
        :rtype: Resource
        """
        return self._resource

    @resource.setter
    def resource(self, resource: Resource):
        """Sets the resource of this SuccessBookingGet.


        :param resource: The resource of this SuccessBookingGet.
        :type resource: Resource
        """

        self._resource = resource

    @property
    def person(self) -> Person:
        """Gets the person of this SuccessBookingGet.


        :return: The person of this SuccessBookingGet.
        :rtype: Person
        """
        return self._person

    @person.setter
    def person(self, person: Person):
        """Sets the person of this SuccessBookingGet.


        :param person: The person of this SuccessBookingGet.
        :type person: Person
        """

        self._person = person
